In [1]:
from raster import *
from utils import *

In [11]:
read_svg("tests/test2.svg")[1].pts

array([[205.021, 153.201],
       [132.837,  72.804]])

In [5]:
list(bounding_box_pixels((0,0), (10, 10)))

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (0, 10),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (2, 10),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (3, 5),
 (3, 6),
 (3, 7),
 (3, 8),
 (3, 9),
 (3, 10),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (4, 5),
 (4, 6),
 (4, 7),
 (4, 8),
 (4, 9),
 (4, 10),
 (5, 0),
 (5, 1),
 (5, 2),
 (5, 3),
 (5, 4),
 (5, 5),
 (5, 6),
 (5, 7),
 (5, 8),
 (5, 9),
 (5, 10),
 (6, 0),
 (6, 1),
 (6, 2),
 (6, 3),
 (6, 4),
 (6, 5),
 (6, 6),
 (6, 7),
 (6, 8),
 (6, 9),
 (6, 10),
 (7, 0),
 (7, 1),
 (7, 2),
 (7, 3),
 (7, 4),
 (7, 5),
 (7, 6),
 (7, 7),
 (7, 8),
 (7, 9),
 (7, 10),
 (8, 0),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (8, 5),
 (8, 6),
 (8, 7),
 (8, 8),
 (8, 9),
 (8, 10),
 (9, 0),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4),
 (9, 5),
 (9, 6),
 (9, 7),
 (9, 8),
 (9, 9),
 (9, 10),


In [11]:
xs = list(map(lambda p: int(p[0]), t.pts))
ys = list(map(lambda p: int(p[1]), t.pts))
((min(xs), min(ys)), (max(xs), max(ys)))


((133, 98), (253, 188))

In [2]:
svg = read_svg("tests/test1.svg")
t = svg[1]
print(t.pts)
# print(bounding_box(t))
xs = map(lambda p: p[0], t.pts)
print(max(list(xs)))

[[193.609  98.891]
 [253.816 188.605]
 [133.401 188.605]
 [193.609  98.891]]
253.816


In [4]:
line = t.pts[0:2]
print(p)
print(line)
~(p == line).all(axis=1).any()
# A point is not in the array
# An array is not contained in the list of arrays
# ~(An array is contained in the list of arrays)
# print(list(p) in list(line))

[133.401 188.605]
[[193.609  98.891]
 [253.816 188.605]]


True

In [5]:
list(filter(lambda p: list(p) not in list(line), triangle_points))

NameError: name 'triangle_points' is not defined

In [8]:
line = t.pts[0:2]
triangle_points = t.pts

p1, p2 = line
for x, y in filter(lambda p: p not in line, triangle_points):
	# Triangle point is above the line region,
	# so our "inside" region will be above the line to.
	if line_y(p1, p2, x) < y:
		print("a")
	# "Inside" region is below the line.
	else:
		print("b")

In [10]:
get_triangle_coverage_for_pixel(t, 200, 189)

0.0

In [2]:
# Tests for line function
line_y((0,0), (1,20), 0.5)

10.0

In [14]:
xs = list(map(lambda p: p[0], t.pts))
ys = list(map(lambda p: p[1], t.pts))
print ( (min(xs), min(ys)), (max(xs), max(ys)) )
    

(133.401, 98.891) (253.816, 188.605)


In [2]:
# Tests for seeing if a point is in a triangle
check_if_point_in_triangle(triangle, 2, 4)

NameError: name 'triangle' is not defined

In [ ]:
triangle[2:2+2]

[(2, 7), (1, 1)]

In [ ]:
import numpy as np